import { useState } from 'react';
import { Modal, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import type { Habit, HabitDraft, HabitType } from './types';
import { useHabitly } from '../app/AppProvider';
import { Button, Card } from '../../components/ui/Primitives';
import { palette } from '../../theme/tokens';

const types:HabitType[]=['boolean','quantity','duration','counter'];const icons=['💧','🏃','📖','🌱','🧘','✍️','🎨','💊'];const colors=['#8570EE','#F6C75A','#71B99C','#F08BA2','#73AAE8'];
export function HabitForm({visible,onClose,habit}:{visible:boolean;onClose:()=>void;habit?:Habit}){const {saveHabit}=useHabitly();const [name,setName]=useState(habit?.name??'');const [icon,setIcon]=useState(habit?.icon??'🌱');const [color,setColor]=useState(habit?.color??colors[0]);const [type,setType]=useState<HabitType>(habit?.type??'boolean');const [target,setTarget]=useState(String(habit?.target??1));const [unit,setUnit]=useState(habit?.unit??'times');const [schedule,setSchedule]=useState<number[]>(habit?.schedule??[0,1,2,3,4,5,6]);const [error,setError]=useState('');
const close=()=>{setError('');onClose()};const save=async()=>{if(!name.trim()){setError('Give your habit a name to continue.');return;}const amount=Number(target);if(type!=='boolean'&&(!Number.isFinite(amount)||amount<=0)){setError('Target must be greater than zero.');return;}if(!schedule.length){setError('Choose at least one day.');return;}const draft:HabitDraft={name:name.trim(),icon,color,type,target:type==='boolean'?1:amount,unit:type==='boolean'?'times':unit.trim()||'times',schedule};await saveHabit(draft,habit?.id);close();};
return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={close}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:22,gap:16,backgroundColor:palette.canvas,flexGrow:1}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Text style={{fontSize:24,fontWeight:'800',color:palette.ink}}>{habit?'Edit habit':'Create a habit'}</Text><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={close}><Text style={{fontSize:26,color:palette.muted}}>×</Text></Pressable></View><Card style={{gap:12}}><Text style={{fontWeight:'700',color:palette.ink}}>Name</Text><TextInput value={name} onChangeText={setName} placeholder="e.g. Read every day" maxLength={50} style={input}/><Text style={{fontWeight:'700',color:palette.ink}}>Choose an icon</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>{icons.map(x=><Pressable key={x} onPress={()=>setIcon(x)} style={{padding:10,borderRadius:14,backgroundColor:x===icon?palette.purpleSoft:palette.surfaceSoft}}><Text style={{fontSize:24}}>{x}</Text></Pressable>)}</View><Text style={{fontWeight:'700',color:palette.ink}}>Accent</Text><View style={{flexDirection:'row',gap:12}}>{colors.map(x=><Pressable key={x} accessibilityLabel={`Choose ${x}`} onPress={()=>setColor(x)} style={{width:32,height:32,borderRadius:16,backgroundColor:x,borderWidth:x===color?3:0,borderColor:palette.ink}}/>)}</View></Card><Card style={{gap:12}}><Text style={{fontWeight:'700',color:palette.ink}}>Tracking style</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{types.map(x=><Pressable key={x} onPress={()=>setType(x)} style={{paddingVertical:10,paddingHorizontal:13,borderRadius:20,backgroundColor:type===x?palette.purpleSoft:palette.surfaceSoft}}><Text style={{color:palette.ink,fontWeight:'600'}}>{x[0].toUpperCase()+x.slice(1)}</Text></Pressable>)}</View>{type!=='boolean'&&<View style={{flexDirection:'row',gap:10}}><TextInput value={target} onChangeText={setTarget} keyboardType="decimal-pad" placeholder="Target" style={[input,{flex:1}]}/><TextInput value={unit} onChangeText={setUnit} placeholder="Unit" style={[input,{flex:1}]}/></View>}<Text style={{fontWeight:'700',color:palette.ink}}>Repeat</Text><View style={{flexDirection:'row',justifyContent:'space-between'}}>{['S','M','T','W','T','F','S'].map((d,i)=><Pressable key={`${d}${i}`} onPress={()=>setSchedule(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i])} style={{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:schedule.includes(i)?palette.purple:palette.canvas}}><Text style={{fontWeight:'700',color:schedule.includes(i)?palette.onPrimary:palette.muted}}>{d}</Text></Pressable>)}</View></Card>{!!error&&<Text accessibilityRole="alert" style={{color:palette.danger}}>{error}</Text>}<Button label={habit?'Save changes':'Create habit'} onPress={()=>void save()}/></ScrollView></Modal>}
const input={height:50,borderRadius:15,backgroundColor:palette.surfaceSoft,paddingHorizontal:14,fontSize:15,color:palette.ink} as const;
