import { Pressable, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { router } from 'expo-router';
import type { Habit } from './types';
import { useHabitly } from '../app/AppProvider';
import { palette } from '../../theme/tokens';
import { Card, ProgressBar } from '../../components/ui/Primitives';
import { dateKey } from '../../utils/dates';
import { appRoute } from '../../utils/routes';
export function HabitRow({habit,date=dateKey(),onManage}:{habit:Habit;date?:string;onManage?:()=>void}){const {entries,setEntry}=useHabitly();const entry=entries.find(e=>e.habitId===habit.id&&e.date===date);const done=Boolean(entry?.completed);const current=entry?.value??0;const progress=habit.type==='boolean'?(done?100:0):Math.min(100,(current/habit.target)*100);const detail=()=>router.push(appRoute({pathname:'/habit/[id]',params:{id:habit.id}}));return <Card style={{padding:12}}><View style={{flexDirection:'row',alignItems:'center',gap:8}}><Pressable onPress={detail} accessibilityRole="button" accessibilityLabel={`${habit.name}, open details`} style={{width:44,height:44,backgroundColor:habit.color+'30',borderRadius:14,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:22}}>{habit.icon}</Text></Pressable><Pressable onPress={detail} style={{flex:1,minHeight:44,justifyContent:'center'}}><Text numberOfLines={1} style={{fontWeight:'700',fontSize:14,color:palette.ink}}>{habit.name}</Text><Text style={{fontSize:12,color:palette.muted,marginTop:3}}>{habit.type==='boolean'?'Daily habit':`${current} / ${habit.target} ${habit.unit}`}</Text></Pressable>{habit.type!=='boolean'&&<Pressable accessibilityRole="button" accessibilityLabel={`Decrease ${habit.name}`} onPress={()=>void setEntry(habit,Math.max(0,current-1),date)} style={{width:40,height:40,borderRadius:12,backgroundColor:palette.surfaceSoft,alignItems:'center',justifyContent:'center'}}><MaterialCommunityIcons name="minus" size={19} color={palette.ink}/></Pressable>}<Pressable accessibilityRole="checkbox" accessibilityState={{checked:done}} accessibilityLabel={`Mark ${habit.name} ${done?'incomplete':'complete'} for ${date}`} onPress={()=>{void Haptics.selectionAsync();void setEntry(habit,habit.type==='boolean'?1:done?0:habit.target,date);}} style={{width:44,height:44,borderRadius:13,borderWidth:1.5,borderColor:done?palette.purple:palette.line,backgroundColor:done?palette.purple:palette.card,alignItems:'center',justifyContent:'center'}}><MaterialCommunityIcons name={done?'check':'circle-outline'} size={21} color={done?palette.onPrimary:palette.muted}/></Pressable>{habit.type!=='boolean'&&<Pressable accessibilityRole="button" accessibilityLabel={`Increase ${habit.name}`} onPress={()=>void setEntry(habit,current+1,date)} style={{width:40,height:40,borderRadius:12,backgroundColor:palette.purpleSoft,alignItems:'center',justifyContent:'center'}}><MaterialCommunityIcons name="plus" size={19} color={palette.purple}/></Pressable>}{onManage&&<Pressable accessibilityRole="button" accessibilityLabel={`Manage ${habit.name}`} onPress={onManage} style={{width:40,height:40,alignItems:'center',justifyContent:'center'}}><MaterialCommunityIcons name="dots-vertical" size={20} color={palette.muted}/></Pressable>}</View>{habit.type!=='boolean'&&<View style={{marginTop:10,marginLeft:52}}><ProgressBar value={progress} color={habit.color}/></View>}</Card>}
