import { Pressable, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import type { Habit } from './types';
import { useHabitly } from '../app/AppProvider';
import { palette } from '../../theme/tokens';
import { Card, ProgressBar } from '../../components/ui/Primitives';
import { dateKey } from '../../utils/dates';
import { appRoute } from '../../utils/routes';
export function HabitRow({habit}:{habit:Habit}){const {entries,setEntry}=useHabitly();const today=entries.find(e=>e.habitId===habit.id&&e.date===dateKey());const done=Boolean(today?.completed);const current=today?.value??0;const progress=habit.type==='boolean'?(done?100:0):Math.min(100,(current/habit.target)*100);const detail=()=>router.push(appRoute({pathname:'/habit/[id]',params:{id:habit.id}}));return <Card style={{padding:14}}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><Pressable onPress={detail} accessibilityRole="button" accessibilityLabel={`${habit.name}, open details`} style={{width:48,height:48,backgroundColor:habit.color+'30',borderRadius:17,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:25}}>{habit.icon}</Text></Pressable><Pressable onPress={detail} style={{flex:1}}><Text style={{fontWeight:'700',fontSize:15,color:palette.ink}}>{habit.name}</Text><Text style={{fontSize:12,color:palette.muted,marginTop:3}}>{habit.type==='boolean'?'Daily habit':`${current} / ${habit.target} ${habit.unit}`}</Text></Pressable>{habit.type!=='boolean'&&<Pressable accessibilityRole="button" accessibilityLabel={`Decrease ${habit.name}`} onPress={()=>void setEntry(habit,Math.max(0,current-1))} style={{width:30,height:30,borderRadius:15,backgroundColor:'#F4F1FA',alignItems:'center',justifyContent:'center'}}><Text style={{color:palette.ink,fontSize:18}}>−</Text></Pressable>}<Pressable accessibilityRole="checkbox" accessibilityState={{checked:done}} accessibilityLabel={`Mark ${habit.name} ${done?'incomplete':'complete'}`} onPress={()=>{void Haptics.selectionAsync();void setEntry(habit,habit.type==='boolean'?1:done?0:habit.target);}} style={{width:34,height:34,borderRadius:17,borderWidth:2,borderColor:done?palette.purple:'#D9D5E3',backgroundColor:done?palette.purple:'white',alignItems:'center',justifyContent:'center'}}><Text style={{color:'white',fontWeight:'800'}}>{done?'✓':''}</Text></Pressable>{habit.type!=='boolean'&&<Pressable accessibilityRole="button" accessibilityLabel={`Increase ${habit.name}`} onPress={()=>void setEntry(habit,current+1)} style={{width:30,height:30,borderRadius:15,backgroundColor:palette.purpleSoft,alignItems:'center',justifyContent:'center'}}><Text style={{color:palette.purple,fontSize:18}}>＋</Text></Pressable>}</View>{habit.type!=='boolean'&&<View style={{marginTop:11,marginLeft:60}}><ProgressBar value={progress} color={habit.color}/></View>}</Card>}
