import { Text, View } from 'react-native';
import { router } from 'expo-router';
import { Card, Header, IconButton, ProgressBar, Screen } from '../../components/ui/Primitives';
import { useHabitly } from '../../features/app/AppProvider';
import { calculateLongestStreak, calculateStreak } from '../../features/habits/domain';
import { bestWeekday, weeklyCompletion } from '../../features/statistics/calculations';
import { palette } from '../../theme/tokens';
import { appRoute } from '../../utils/routes';

export default function Stats(){const {habits,entries}=useHabitly();const active=habits.filter(h=>!h.archived);const current=Math.max(0,...active.map(h=>calculateStreak(h,entries)));const longest=Math.max(0,...active.map(h=>calculateLongestStreak(h,entries)));const total=entries.filter(e=>e.completed).length;const week=weeklyCompletion(active,entries);const month=Array.from({length:4},(_,i)=>weeklyCompletion(active,entries,i)).reduce((a,b)=>a+b,0)/4;return <Screen safeBottom={false}><Header title="Your progress" subtitle="Every small win adds up." right={<IconButton label="⚙" accessibilityLabel="Settings" onPress={()=>router.push(appRoute('/settings'))}/>} /><Card style={{gap:13}}><Text style={{fontWeight:'700',color:palette.ink}}>Overall consistency</Text><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><Text style={{fontSize:36,fontWeight:'900',color:palette.ink}}>{week}%</Text><View style={{flexDirection:'row',alignItems:'flex-end',gap:6,height:54}}>{[38,60,47,78,54,90,week||12].map((h,i)=><View key={i} style={{width:17,height:h/1.8,borderRadius:7,backgroundColor:i===6?palette.purple:palette.purpleSoft}}/>)}</View></View><ProgressBar value={week}/><Text style={{fontSize:12,color:palette.muted}}>This week’s scheduled habit completion</Text></Card><View style={{flexDirection:'row',gap:10}}>{[[`${current}`,'Current streak','🔥'],[`${longest}`,'Longest streak','🏆']].map(([n,l,icon])=><Card key={l} style={{flex:1,gap:7}}><Text style={{fontSize:21}}>{icon}</Text><Text style={{fontSize:28,fontWeight:'900',color:palette.ink}}>{n}</Text><Text style={{fontSize:12,color:palette.muted}}>{l}</Text></Card>)}</View><View style={{flexDirection:'row',gap:10}}>{[[`${total}`,'Total check-ins','✅'],[bestWeekday(active,entries),'Best weekday','✨']].map(([n,l,icon])=><Card key={l} style={{flex:1,gap:7}}><Text style={{fontSize:21}}>{icon}</Text><Text style={{fontSize:20,fontWeight:'800',color:palette.ink}}>{n}</Text><Text style={{fontSize:12,color:palette.muted}}>{l}</Text></Card>)}</View><Card style={{gap:13}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{fontWeight:'700',color:palette.ink}}>Monthly rhythm</Text><Text style={{color:palette.purple,fontWeight:'700'}}>{Math.round(month)}% avg.</Text></View><View style={{height:110,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-around'}}>{[0,1,2,3].map(i=><View key={i} style={{alignItems:'center',gap:6}}><View style={{width:40,height:Math.max(8,[0,1,2,3].map(x=>weeklyCompletion(active,entries,3-x))[i]*.9),backgroundColor:i===3?palette.purple:palette.purpleSoft,borderRadius:10}}/><Text style={{fontSize:11,color:palette.muted}}>{['W1','W2','W3','W4'][i]}</Text></View>)}</View></Card><Text style={{fontSize:12,textAlign:'center',color:palette.muted}}>Your data stays private on this device.</Text></Screen>}
