import { Text, View } from 'react-native';
import { router } from 'expo-router';
import { Card, Header, IconButton, ProgressBar, Screen, SectionTitle } from '../../components/ui/Primitives';
import { HabitRow } from '../../features/habits/HabitRow';
import { useHabitly } from '../../features/app/AppProvider';
import { palette } from '../../theme/tokens';
import { dateKey, shortDate } from '../../utils/dates';
import { appRoute } from '../../utils/routes';

export default function Today(){const {habits,entries,tasks,profileName}=useHabitly();const active=habits.filter(h=>!h.archived&&h.schedule.includes(new Date().getDay()));const done=active.filter(h=>entries.some(e=>e.habitId===h.id&&e.date===dateKey()&&e.completed)).length;const pct=active.length?Math.round(done/active.length*100):0;const todayTasks=tasks.filter(t=>t.dueDate<=dateKey()&&!t.completed);const hour=new Date().getHours();const greet=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';
return <Screen><Header title={`${greet},`} subtitle={`${profileName} 👋 · ${shortDate(dateKey())}`} right={<IconButton label="⌕" accessibilityLabel="Search" onPress={()=>router.push(appRoute('/search'))}/>}/><Card style={{backgroundColor:'#EEE9FF',borderColor:'#EEE9FF',gap:12}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View><Text style={{fontSize:17,fontWeight:'800',color:palette.ink}}>Today’s progress</Text><Text style={{fontSize:13,color:palette.muted,marginTop:5}}>{done} of {active.length} habits completed</Text></View><View style={{width:66,height:66,borderRadius:33,borderWidth:7,borderColor:palette.purple,alignItems:'center',justifyContent:'center',backgroundColor:'white'}}><Text style={{fontSize:16,fontWeight:'800',color:palette.ink}}>{pct}%</Text></View></View><ProgressBar value={pct}/><View style={{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:3}}>{['M','T','W','T','F','S','S'].map((d,i)=><View key={`${d}${i}`} style={{alignItems:'center',gap:5}}><View style={{width:9,height:9,borderRadius:5,backgroundColor:i===new Date().getDay()?palette.purple:'#CFC7F5'}}/><Text style={{fontSize:10,color:palette.muted}}>{d}</Text></View>)}</View></Card><Card style={{backgroundColor:'#FFF3D0',borderColor:'#FFF3D0',paddingVertical:13}}><Text style={{fontWeight:'800',fontSize:14,color:palette.ink}}>🔥  Keep your streak going <Text style={{fontWeight:'500'}}> · one day at a time</Text></Text></Card><SectionTitle>Today’s habits</SectionTitle>{active.length?active.map(h=><HabitRow key={h.id} habit={h}/>):<Card><Text style={{color:palette.muted}}>No habits scheduled today. Add one from Habits.</Text></Card>}<SectionTitle aside={<Text onPress={()=>router.push(appRoute('/(tabs)/tasks'))} style={{color:palette.purple,fontWeight:'700'}}>See all</Text>}>Tasks for today</SectionTitle>{todayTasks.length?<Card style={{gap:14}}>{todayTasks.slice(0,3).map(task=><View key={task.id} style={{flexDirection:'row',alignItems:'center',gap:10}}><View style={{width:23,height:23,borderRadius:8,backgroundColor:palette.purpleSoft,alignItems:'center',justifyContent:'center'}}><Text>□</Text></View><Text style={{fontSize:14,color:palette.ink}}>{task.title}</Text></View>)}</Card>:<Card><Text style={{color:palette.muted}}>You’re all caught up ✨</Text></Card>}</Screen>}
