import { useMemo } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Text, View } from 'react-native';
import { Card, Header, IconButton, ProgressBar, Screen } from '../../components/ui/Primitives';
import { useHabitly } from '../../features/app/AppProvider';
import { calculateLongestStreak, calculateStreak, completionRate, heatmapLevel } from '../../features/habits/domain';
import { palette } from '../../theme/tokens';
import { addDays, dateKey } from '../../utils/dates';

export default function HabitDetail(){const {id}=useLocalSearchParams<{id:string}>();const {habits,entries}=useHabitly();const habit=habits.find(h=>h.id===id);const cells=useMemo(()=>Array.from({length:112},(_,i)=>{const d=addDays(new Date(),i-111);const key=dateKey(d);const entry=entries.find(e=>e.habitId===id&&e.date===key);return {key,level:habit?heatmapLevel(entry,habit):0}}),[entries,id,habit]);if(!habit)return <Screen><Header title="Habit not found" right={<IconButton label="‹" accessibilityLabel="Go back" onPress={()=>router.back()}/>} /></Screen>;const streak=calculateStreak(habit,entries);const longest=calculateLongestStreak(habit,entries);const rate=completionRate(entries,habit.id);const colors=['#F0EDF6','#E2DCFF','#C5B8FF','#A28DFF',palette.purple];
return <Screen><Header title="Habit details" right={<IconButton label="‹" accessibilityLabel="Go back" onPress={()=>router.back()}/>} /><View style={{flexDirection:'row',alignItems:'center',gap:14}}><View style={{width:66,height:66,borderRadius:23,alignItems:'center',justifyContent:'center',backgroundColor:habit.color+'35'}}><Text style={{fontSize:34}}>{habit.icon}</Text></View><View><Text style={{fontSize:24,fontWeight:'800',color:palette.ink}}>{habit.name}</Text><Text style={{color:palette.muted,marginTop:4}}>{habit.schedule.length===7?'Every day':`${habit.schedule.length} days a week`}</Text></View></View><View style={{flexDirection:'row',gap:10}}>{[[`${streak} days`,'Current streak'],[`${longest} days`,'Longest streak']].map(([n,l])=><Card key={l} style={{flex:1}}><Text style={{fontSize:23,fontWeight:'800',color:palette.ink}}>{n}</Text><Text style={{fontSize:12,color:palette.muted,marginTop:4}}>{l}</Text></Card>)}</View><Card style={{gap:10}}><Text style={{fontWeight:'800',color:palette.ink}}>Completion rate</Text><View style={{flexDirection:'row',alignItems:'center',gap:12}}><Text style={{fontSize:28,fontWeight:'800',color:palette.ink}}>{rate}%</Text><View style={{flex:1}}><ProgressBar value={rate} color={habit.color}/></View></View></Card><Card style={{gap:14}}><Text style={{fontWeight:'800',color:palette.ink}}>Your consistency</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:5}}>{cells.map(c=><View key={c.key} accessibilityLabel={`${c.key}, level ${c.level}`} style={{width:17,height:17,borderRadius:5,backgroundColor:colors[c.level]}}/>)}</View><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{fontSize:11,color:palette.muted}}>112 days</Text><Text style={{fontSize:11,color:palette.muted}}>Today</Text></View></Card><Card style={{gap:11}}><Text style={{fontWeight:'800',color:palette.ink}}>Schedule</Text><View style={{flexDirection:'row',justifyContent:'space-between'}}>{['S','M','T','W','T','F','S'].map((d,i)=><View key={`${d}${i}`} style={{width:32,height:32,borderRadius:16,backgroundColor:habit.schedule.includes(i)?palette.purpleSoft:'#F7F5FA',alignItems:'center',justifyContent:'center'}}><Text style={{fontWeight:'700',color:habit.schedule.includes(i)?palette.purple:palette.muted}}>{d}</Text></View>)}</View></Card></Screen>}
