import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View, type ViewStyle } from 'react-native';
import { palette } from '../../theme/tokens';

export function Screen({children,style}:{children:React.ReactNode;style?:ViewStyle}) { return <ScrollView style={{flex:1,backgroundColor:palette.canvas}} contentContainerStyle={[styles.screen,style]} showsVerticalScrollIndicator={false}>{children}</ScrollView>; }
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle}) { return <View style={[styles.card,{backgroundColor:palette.card,borderColor:palette.line},style]}>{children}</View>; }
export function SectionTitle({children,aside}:{children:string;aside?:React.ReactNode}) { return <View style={styles.section}><Text style={[styles.sectionText,{color:palette.ink}]}>{children}</Text>{aside}</View>; }
export function Button({label,onPress,secondary,style}:{label:string;onPress:()=>void;secondary?:boolean;style?:ViewStyle}) { return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[styles.button,{backgroundColor:secondary?palette.purpleSoft:palette.ink},style,pressed&&{opacity:.82,transform:[{scale:.99}]}]}><Text style={[styles.buttonText,{color:secondary?palette.ink:'#FFF'}]}>{label}</Text></Pressable>; }
export function IconButton({label,onPress,accessibilityLabel}:{label:string;onPress:()=>void;accessibilityLabel:string}) { return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel} onPress={onPress} style={({pressed})=>[styles.iconButton,{backgroundColor:palette.purpleSoft},pressed&&{opacity:.7}]}><Text style={{fontSize:23,color:palette.ink}}>{label}</Text></Pressable>; }
export function Header({title,subtitle,right}:{title:string;subtitle?:string;right?:React.ReactNode}) { return <View style={styles.header}><View style={{flex:1}}><Text style={[styles.title,{color:palette.ink}]}>{title}</Text>{subtitle&&<Text style={[styles.subtitle,{color:palette.muted}]}>{subtitle}</Text>}</View>{right}</View>; }
export function ProgressBar({value,color=palette.purple}:{value:number;color?:string}) { return <View style={[styles.track,{backgroundColor:palette.line}]}><View style={[styles.fill,{width:`${Math.max(0,Math.min(100,value))}%`,backgroundColor:color}]} /></View>; }
const styles=StyleSheet.create({screen:{paddingHorizontal:20,paddingTop:18,paddingBottom:34,gap:18},card:{backgroundColor:palette.card,borderRadius:24,padding:18,borderWidth:1,borderColor:'#F0EDF5'},section:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:-8},sectionText:{fontSize:18,fontWeight:'700',color:palette.ink},button:{backgroundColor:palette.ink,borderRadius:28,minHeight:52,alignItems:'center',justifyContent:'center',paddingHorizontal:22},buttonText:{color:'#FFF',fontSize:15,fontWeight:'700'},secondary:{backgroundColor:palette.purpleSoft},secondaryText:{color:palette.ink},iconButton:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:palette.purpleSoft},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:2},title:{fontSize:28,fontWeight:'800',letterSpacing:-.7,color:palette.ink},subtitle:{fontSize:14,color:palette.muted,marginTop:5},track:{height:8,backgroundColor:'#F0EDF7',borderRadius:8,overflow:'hidden'},fill:{height:'100%',borderRadius:8}});
